name: qiscus_chat_sdk
description: The Scalable In-App Chat SDK for Mobile & Web
version: 1.0.7
homepage: https://sdk.qiscus.com
repository: https://github.com/qiscus/qiscus-chat-sdk-flutter
issue_tracker: https://github.com/qiscus/qiscus-chat-sdk-flutter/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  sealed_unions: ^3.0.2+2
  async: ^2.4.1
  meta: ^1.1.8
  dartz: ^0.9.1
  mqtt_client: ^6.0.0
  dio: ^3.0.8
  equatable: ^1.1.1
  pretty_dio_logger: ^1.1.1
  get_it: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  grinder: ^0.8.5
  build_runner: ^1.8.0
  mockito: ^4.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
  test_coverage: ^0.4.3
  clock: ^1.0.1
  fake_async: ^1.1.0
