name: qiscus_chat_sdk
description: A starting point for Dart libraries or applications.
version: 1.0.0+alpha4
homepage: https://sdk.qiscus.com
repository: https://github.com/qiscus/qiscus-chat-sdk-flutter
issue_tracker: https://github.com/qiscus/qiscus-chat-sdk-flutter/issues

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  sealed_unions: ^3.0.2+2
  json_annotation: ^3.0.1
  async: ^2.4.0
  meta: ^1.1.8
  dartz: ^0.8.9
  mqtt_client: ^6.0.0
  retrofit: ^1.3.0
  logger: ^0.8.3
  dio: ^3.0.8
  equatable: ^1.1.1
  pretty_dio_logger: ^1.1.1
  flutter:
    sdk: flutter
  get_it: ^4.0.1

dev_dependencies:
  json_serializable: ^3.2.5
  retrofit_generator: ^1.3.1+4
  build_runner: ^1.8.0
  mockito: ^4.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
  flutter_test:
    sdk: flutter

