name: qiscus_chat_sdk
description: The Scalable In-App Chat SDK for Mobile & Web
version: 2.0.0-beta.2
homepage: https://sdk.qiscus.com
repository: https://github.com/qiscus/qiscus-chat-sdk-flutter
issue_tracker: https://github.com/qiscus/qiscus-chat-sdk-flutter/issues

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  sealed_unions: ^3.0.2+2
  async: ^2.8.2
  mqtt_client: ^9.4.2
  dio: ^4.0.0
  equatable: ^2.0.3
  pretty_dio_logger: ^1.1.1
  fpdart: ^0.0.12
  riverpod: ^2.0.0-dev.4
  freezed_annotation: ^2.0.3

dev_dependencies:
  build_runner: ^2.1.0
  mockito: ^5.0.13
  pedantic: ^1.8.0
  test: ^1.21.1
  fake_async: ^1.3.0
  freezed: ^2.0.3
